# 公共配置文件（环境无关的配置放这里）
spring:
  application:
    name: guooj-backend
  # 默认 dev 环境，打包上线时用 --spring.profiles.active=prod 切换
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.itguo.guooj.controller
# 代码沙箱配置
codesandbox:
  type: remote
